### ISSUE TITLE
Trello/ClickUp support?

### ISSUE THREAD

**Issue by kerryj89** [JSanchezIO/conventional-changelog-ghostwriter#1]
I see in the description that conventional-changelog-ghostwriter supports Trello? So I take it that it doesn't stop matching prematurely like [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog/issues/650)?  Or maybe I misunderstood when Trello was mentioned.

**Comment by JSanchezIO** [comment]
I haven't actually tested Trello and should remove it from the `README.md`. However, I'm confident that using a configuration similar to the following you should be able to support ClickUp:

```js
module.exports = {
  issueUrlFormat: 'https://app.clickup.com/t/{{ISSUE_NUMBER}}',
  issuePrefixes: ['CU-'],
};
```

Then making a commit such as the following: (you can make this easier by using [cz-ghostwriter](https://github.com/JSanchezIO/cz-ghostwriter))

```
fix(some-scope): add awesome feature

for #CU-rk45gv
```

If this doesn't work then I'm happy to build out support for this. I know how frustrating it can be for your tooling to not link together, and that's the main pain point ghostwriter is aimed at solving.

**Comment by kerryj89** [comment]
Thanks for replying!

Before I try, this is what I had already set up with `conventional-changelog-conventionalcommits`:

```
issueUrlFormat: 'https://app.clickup.com/t/{{id}}',
issuePrefixes: ['CU-', 'cu-'],
commitUrlFormat: '{{host}}/{{owner}}/{{repository}}/commits/{{hash}}',
compareUrlFormat: '{{host}}/{{owner}}/{{repository}}/branches/compare/{{currentTag}}%0D{{previousTag}}'
```

Does your library parse the issue prefixes more intelligently in that it _doesn't_ assume that the ticket/issue id never ends in letters, which is the case of GitHub and BitBucket but not true for other issue tracking systems?  I don't understand why they didn't just end the match on the first space character following the prefix instead...

**Comment by JSanchezIO** [comment]
We don't do anything different for the `#` issuePrefix. However, if you use your own we create a Regular Expression that will stop at the first space as you've said.

https://github.com/JSanchezIO/conventional-changelog-ghostwriter/blob/main/src/writer-opts.ts#L36-L44

```ts
nonNativeIssuePrefixes = context.config.issuePrefixes
      .filter((issuePrefix) => issuePrefix !== '#')
      .map((issuePrefix) => {
        return {
          issuePrefix,
          regExp: new RegExp(`${issuePrefix}(\\S+)`),
        };
      });
  }
```

**Comment by kerryj89** [comment]
I am trying to get this to work with my Lerna setup.

**lerna.json**
```
{
  "version": "independent",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "command": {
    "version": {
      "conventionalCommits": true,
      "tagVersionPrefix": "",
      "message": "chore(release): Publish [skip ci]",
      "changelogPreset": {
        "name": "conventional-changelog-ghostwriter"
      },
      "ignoreChanges": ["**/*.md"],
      "allowBranch": "master"
    }
  }
}
```

Wanting to keep it the same experience as the previous changelog preset, I copied the types from [conventional-changelog-conventionalcommits](https://github.com/conventional-changelog/conventional-changelog/blob/f1f50f56626099e92efe31d2f8c5477abd90f1b7/packages/conventional-changelog-conventionalcommits/writer-opts.js#L179-L192) options:

**.changelogrc.js**
```
module.exports = {
    issueUrlFormat: 'https://app.clickup.com/t/{{id}}',
    issuePrefixes: ['CU-', 'cu-'],
    commitUrlFormat: '{{host}}/{{owner}}/{{repository}}/commits/{{hash}}',
    compareUrlFormat: '{{host}}/{{owner}}/{{repository}}/branches/compare/{{currentTag}}%0D{{previousTag}}',
    types: [
        {
            description: 'A new feature',
            section: 'Features',
            type: 'feat'
        },
        {
            description: 'A new feature',
            section: 'Features',
            type: 'feature'
        },
        {
            description: 'A bug fix',
            section: 'Bug Fixes',
            type: 'fix'
        },
        {
            description: 'A code change that improves performance',
            section: 'Performance Improvements',
            type: 'perf'
        },
        {
            description: 'A revert',
            section: 'Reverts',
            type: 'revert'
        },
        {
            description: 'Documentation only changes'
            hidden: true,
            type: 'docs'
        },
        {
            description: 'Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)',
            hidden: true,
            type: 'style'
        },
        {
            description: 'Changes to the build process or auxiliary tools and libraries',
            hidden: true,
            type: 'chore'
        },
        {
            description: "A code change that neither fixes a bug nor adds a feature",
            hidden: true,
            type: 'refactor'
        },
        {
            description: 'Adding missing or correcting existing tests',
            hidden: true,
            type: 'test'
        },
        {
            description: 'Changes to the build process',
            hidden: true,
            type: 'build'
        },
        {
            description: 'Changes to the continuous integration process',
            hidden: true,
            type: 'ci'
        }
    ],
};
```

This config errors out:
```
lerna ERR! /opt/atlassian/pipelines/agent/build/.changelogrc.js:34
lerna ERR!             hidden: true,
lerna ERR!             ^^^^^^
lerna ERR! 
lerna ERR! SyntaxError: Unexpected identifier
lerna ERR!     at Object.compileFunction (node:vm:352:18)
lerna ERR!     at wrapSafe (node:internal/modules/cjs/loader:1025:15)
lerna ERR!     at Module._compile (node:internal/modules/cjs/loader:1059:27)
lerna ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
lerna ERR!     at Module.load (node:internal/modules/cjs/loader:975:32)
lerna ERR!     at Function.Module._load (node:internal/modules/cjs/loader:816:12)
lerna ERR!     at Module.require (node:internal/modules/cjs/loader:999:19)
lerna ERR!     at require (node:internal/modules/cjs/helpers:93:18)
lerna ERR!     at Object.getConfiguration (/root/.nvm/versions/node/v16.4.1/lib/node_modules/conventional-changelog-ghostwriter/dist/configuration.js:19:11)
lerna ERR! /opt/atlassian/pipelines/agent/build/.changelogrc.js:34
lerna ERR!             hidden: true,
lerna ERR!             ^^^^^^
lerna ERR! 
lerna ERR! SyntaxError: Unexpected identifier
lerna ERR!     at Object.compileFunction (node:vm:352:18)
lerna ERR!     at wrapSafe (node:internal/modules/cjs/loader:1025:15)
lerna ERR!     at Module._compile (node:internal/modules/cjs/loader:1059:27)
lerna ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
lerna ERR!     at Module.load (node:internal/modules/cjs/loader:975:32)
lerna ERR!     at Function.Module._load (node:internal/modules/cjs/loader:816:12)
lerna ERR!     at Module.require (node:internal/modules/cjs/loader:999:19)
lerna ERR!     at require (node:internal/modules/cjs/helpers:93:18)
lerna ERR!     at Object.getConfiguration (/root/.nvm/versions/node/v16.4.1/lib/node_modules/conventional-changelog-ghostwriter/dist/configuration.js:19:11)
lerna ERR! lerna Error in conventional-changelog-writer: Unexpected identifier
```

I tried using your [.changelogrc.js](https://github.com/JSanchezIO/conventional-changelog-ghostwriter/blob/main/.changelogrc.js) example and got the following error:
```
lerna ERR! Error: Error in conventional-changelog-writer: You must provide a commitUrlFormat
lerna ERR!     at Object.getConfiguration (/root/.nvm/versions/node/v16.4.1/lib/node_modules/conventional-changelog-ghostwriter/dist/configuration.js:39:15)
lerna ERR!     at transform (/root/.nvm/versions/node/v16.4.1/lib/node_modules/conventional-changelog-ghostwriter/dist/writer-opts.js:22:46)
lerna ERR!     at Object.processCommit (/root/.nvm/versions/node/v16.4.1/lib/node_modules/lerna/node_modules/conventional-changelog-writer/lib/util.js:120:14)
lerna ERR!     at Transform._transform (/root/.nvm/versions/node/v16.4.1/lib/node_modules/lerna/node_modules/conventional-changelog-writer/index.js:93:27)
lerna ERR!     at Transform._read (/root/.nvm/versions/node/v16.4.1/lib/node_modules/lerna/node_modules/readable-stream/lib/_stream_transform.js:177:10)
lerna ERR!     at Transform._write (/root/.nvm/versions/node/v16.4.1/lib/node_modules/lerna/node_modules/readable-stream/lib/_stream_transform.js:164:83)
lerna ERR!     at doWrite (/root/.nvm/versions/node/v16.4.1/lib/node_modules/lerna/node_modules/readable-stream/lib/_stream_writable.js:409:139)
lerna ERR!     at writeOrBuffer (/root/.nvm/versions/node/v16.4.1/lib/node_modules/lerna/node_modules/readable-stream/lib/_stream_writable.js:398:5)
lerna ERR!     at Transform.Writable.write (/root/.nvm/versions/node/v16.4.1/lib/node_modules/lerna/node_modules/readable-stream/lib/_stream_writable.js:307:11)
lerna ERR! Error: Error in conventional-changelog-writer: You must provide a commitUrlFormat
lerna ERR!     at Object.getConfiguration (/root/.nvm/versions/node/v16.4.1/lib/node_modules/conventional-changelog-ghostwriter/dist/configuration.js:39:15)
lerna ERR!     at transform (/root/.nvm/versions/node/v16.4.1/lib/node_modules/conventional-changelog-ghostwriter/dist/writer-opts.js:22:46)
lerna ERR!     at Object.processCommit (/root/.nvm/versions/node/v16.4.1/lib/node_modules/lerna/node_modules/conventional-changelog-writer/lib/util.js:120:14)
lerna ERR!     at Transform._transform (/root/.nvm/versions/node/v16.4.1/lib/node_modules/lerna/node_modules/conventional-changelog-writer/index.js:93:27)
lerna ERR!     at Transform._read (/root/.nvm/versions/node/v16.4.1/lib/node_modules/lerna/node_modules/readable-stream/lib/_stream_transform.js:177:10)
lerna ERR!     at Transform._write (/root/.nvm/versions/node/v16.4.1/lib/node_modules/lerna/node_modules/readable-stream/lib/_stream_transform.js:164:83)
lerna ERR!     at doWrite (/root/.nvm/versions/node/v16.4.1/lib/node_modules/lerna/node_modules/readable-stream/lib/_stream_writable.js:409:139)
lerna ERR!     at writeOrBuffer (/root/.nvm/versions/node/v16.4.1/lib/node_modules/lerna/node_modules/readable-stream/lib/_stream_writable.js:398:5)
lerna ERR!     at Transform.Writable.write (/root/.nvm/versions/node/v16.4.1/lib/node_modules/lerna/node_modules/readable-stream/lib/_stream_writable.js:307:11)
lerna ERR! lerna Error in conventional-changelog-writer: You must provide a commitUrlFormat
```

I'll admit I don't really know what the intricacies of the changelogging system, do you see anything I'm doing wrong?

**Comment by JSanchezIO** [comment]
In your `.changelogrc.js` file you're missing a `,` after `description: 'Documentation only changes'`. In my example, I didn't add the other properties that are required as defined in the [README.md](https://github.com/JSanchezIO/conventional-changelog-ghostwriter#configuration). 

Based on what I'm seeing I'd assume the `.changelogrc.js` should be something like:

```js
module.exports = {
    issueUrlFormat: 'https://app.clickup.com/t/{{ISSUE_NUMBER}}',
    issuePrefixes: ['CU-', 'cu-'],
    commitUrlFormat: 'CHANGE_THIS/commits/{{LONG_HASH}}',
    compareUrlFormat: 'CHANGE_THIS/branches/compare/{{CURRENT_TAG}}%0D{{PREVIOUS_TAG}}',
    types: [
        {
            description: 'A new feature',
            section: 'Features',
            type: 'feat'
        },
        {
            description: 'A new feature',
            section: 'Features',
            type: 'feature'
        },
        {
            description: 'A bug fix',
            section: 'Bug Fixes',
            type: 'fix'
        },
        {
            description: 'A code change that improves performance',
            section: 'Performance Improvements',
            type: 'perf'
        },
        {
            description: 'A revert',
            section: 'Reverts',
            type: 'revert'
        },
        {
            description: 'Documentation only changes',
            hidden: true,
            type: 'docs'
        },
        {
            description: 'Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)',
            hidden: true,
            type: 'style'
        },
        {
            description: 'Changes to the build process or auxiliary tools and libraries',
            hidden: true,
            type: 'chore'
        },
        {
            description: 'A code change that neither fixes a bug nor adds a feature',
            hidden: true,
            type: 'refactor'
        },
        {
            description: 'Adding missing or correcting existing tests',
            hidden: true,
            type: 'test'
        },
        {
            description: 'Changes to the build process',
            hidden: true,
            type: 'build'
        },
        {
            description: 'Changes to the continuous integration process',
            hidden: true,
            type: 'ci'
        }
    ],
};
```

I don't know where your source code is hosted so you'll have to update `CHANGE_THIS` to the proper URL. This plugin doesn't currently support the `{{host}}`, `{{owner}}`, or `{{repository}}` template variables, so you'll have to hardcode it.

**Comment by kerryj89** [comment]
Thank you!  That worked mostly, but I'm having a few problems.

My output looks something like:

# [2.2.12](https://bitbucket.org/foo/bar/branches/compare/{{CURRENT_TAG}}%0D{{PREVIOUS_TAG}}) (2021-07-03)

### Bug Fixes

- **css:** Something #CU-zkcam3 [662766e](https://bitbucket.org/foo/bar/commits/662766ec565bc034391eeb6a3daa480b4a3ddc41) for [CU-zkcam3](https://app.clickup.com/t/zkcam3)

\<br /\>

<hr>

I needed to put a # symbol in front of CU-* in the commit in order for it to recognize it as an issue hash (maybe that's required?).  It also outputs a \<br /\> which renders plainly in BitBucket.

So I tried to solve the \<br /\> issue by providing my template files copied over from https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-conventionalcommits/templates and tried using the options to point to the template files.

```
module.exports = {
    commitPartial: 'some/where/commit.hbs',
    headerPartial: 'some/where/header.hbs',
    mainTemplate: 'some/where/template.hbs',
    ...
};
```

Maybe custom templates are out of the scope of ghostwriter and I know what I'm trying is overkill for just being able to link to ClickUp issues properly.  Thanks for the help so far, though.

**Comment by JSanchezIO** [comment]
The requirement of the `#` is defined in the spec for conventional commits, it's under the trailer convention. However, I do agree the need to remember that is frustrating which led me to build [cz-ghostwriter](https://github.com/JSanchezIO/cz-ghostwriter) a commit prompt adapter for [commitizen](https://github.com/commitizen/cz-cli) that will do all the formatting for you. You can even set it up as a git hook so that anytime you run `git commit` it'll run the prompt. 

As for the commit template, we don't support that currently, and before I add something that flexible I'd rather err on the side of caution and allow a flag of `removeVersionSpacing` or something of that sort that will omit the `<br />`. Does that work for you?

**Comment by kerryj89** [comment]
> As for the commit template, we don't support that currently, and before I add something that flexible I'd rather err on the side of specificity and allow a flag of removeVersionSpacing or something of that sort that will omit the <br />. Does that work for you?

That would be great!

**Comment by JSanchezIO** [comment]
[v1.1.0](https://github.com/JSanchezIO/conventional-changelog-ghostwriter/releases/tag/v1.1.0) has been released to address this.

**Comment by JSanchezIO** [comment]
@kerryj89 If everything is working well, feel free to close this issue.

**Comment by kerryj89** [comment]
I have two final issues in my changelog:

- `{{CURRENT_TAG}}` and `{{PREVIOUS_TAG}}` do not get replaced in my CHANGELOG.md whereas they did with conventional-changelog-conventionalcommits. It outputs `https://bitbucket.org/foo/bar/branches/compare/%7B%7BCURRENT_TAG%7D%7D%0D%7B%7BPREVIOUS_TAG%7D%7D`
- I also keep getting `Note: Version bump only for package @org/some-package` at the end of each version note.  I've gotten that message before when the version was upped without any conventional commit message.

Thanks

**Comment by JSanchezIO** [comment]
@kerryj89 Let's break these down into two more issues on GitHub and I'll get started on replication and fixing. Thanks for taking the time to provide this feedback, it'll help others who try to adopt **ghostwriter** in the future.

**Comment by kerryj89** [comment]
@JSanchezIO Done!  Thanks - I've reopened this because it doesn't parse `#CU-x9cdyh` correctly, same symptom of not outputting the full hash.

**Comment by JSanchezIO** [comment]
[v1.1.1](https://github.com/JSanchezIO/conventional-changelog-ghostwriter/releases/tag/v1.1.1) has been released to address this.

**Comment by JSanchezIO** [comment]
@kerryj89 If this issue is resolved, please mark this as closed.
