### ISSUE TITLE
{{CURRENT_TAG}} and {{PREVIOUS_TAG}} are not getting replaced

### ISSUE THREAD

**Issue by kerryj89** [JSanchezIO/conventional-changelog-ghostwriter#2]
`{{CURRENT_TAG}}` and `{{PREVIOUS_TAG}}` do not get replaced in my CHANGELOG.md whereas they did with conventional-changelog-conventionalcommits. It outputs `https://bitbucket.org/foo/bar/branches/compare/%7B%7BCURRENT_TAG%7D%7D%0D%7B%7BPREVIOUS_TAG%7D%7D`

**Comment by JSanchezIO** [comment]
[v1.1.1](https://github.com/JSanchezIO/conventional-changelog-ghostwriter/releases/tag/v1.1.1) has been released to address this.

**Comment by JSanchezIO** [comment]
@kerryj89 If this issue is resolved, please mark this as closed.

**Comment by kerryj89** [comment]
I'll close for now since I won't be able to test for a bit, and will reopen if it's still an issue.  Thanks!
