### ISSUE TITLE
Version bump message shows up on every version

### ISSUE THREAD

**Issue by kerryj89** [JSanchezIO/conventional-changelog-ghostwriter#3]
I keep getting `Note: Version bump only for package @org/some-package` at the end of each version note.  I've gotten that message before when the version was upped without any conventional commit message, but now it always sits underneath any conventional commit messages.  I would like to only display that message if there are no meaningful commit messages.

**Comment by JSanchezIO** [comment]
After some digging on this, it seems Lerna is adding this. Unfortunately, this package can't change that behavior.  The code responsible is located here: https://github.com/lerna/lerna/blob/6cb8ab2d4af7ce25c812e8fb05cd04650105705f/core/conventional-commits/lib/update-changelog.js#L65-L83

My recommendation would be to open an issue on Lerna's repository namely, request some more intelligence be added to the function  `makeBumpOnlyFilter` that will conditionally add the Note if there are no changes for the package.
